# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-06 10:57
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('courses', multiselectfield.db.fields.MultiSelectField(choices=[('py', 'Python'), ('django', 'Django'), ('restapi', 'RestApi'), ('ui', 'UI')], max_length=100)),
                ('location', multiselectfield.db.fields.MultiSelectField(choices=[('hyd', 'HYDERABAD'), ('bang', 'BANGLORE'), ('ind', 'INDORE')], max_length=100)),
                ('shift', multiselectfield.db.fields.MultiSelectField(choices=[('morning', 'MORNING'), ('afternoon', 'AFTERNOON'), ('night', 'NIGHT')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('date', models.DateField()),
                ('feedback', models.CharField(max_length=200)),
            ],
        ),
    ]
